services:
  go-service:
    build: .
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    volumes:
      - ./workspace:/usr/src/app
    ports:
      - "8080:${PORT}"
    tty: true
    stdin_open: true