services:
  go-service:
    build: .
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    env_file:
      - .env  # Load .env into container
    volumes:
      - ./workspace:/usr/src/app
    ports:
      - "8080:${PORT}" # Go application port
      - "5432:5432" # PostgreSQL port
    tty: true
    stdin_open: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5